[window]
# decorations = "None"
opacity = 1
decorations_theme_variant = "Dark"

[shell]
program = "C:\\Program Files\\Git\\bin\\bash.exe"
args = ["--login"]

[font]
normal = { family = "MesloLGM Nerd Font" }
size = 14
